### PR TITLE
Add logger.vim

### PR DESCRIPTION
**Pull request by Freed-Wu**
fix the error cannot find SpaceVim#logger#warn

### CODE REVIEW

**Comment by Freed-Wu** [comment]
in SpaceVim/plugin/manager.vim, there sometimes call SpaceVim#logger#warn(). but logger.vim has left.

**Comment by TamaMcGlinn** [comment]
This looks good. By replacing wsdjeg/dein-ui with Freed-Wu/dein-ui I can confirm this fixes #8 (which should be reopened until this PR is merged)

**Comment by Freed-Wu** [comment]
thanks for your confirmation!

**Comment by Freed-Wu** [comment]
<https://github.com/SpaceVim/SpaceVim/pull/4018> will fix #8.

**Pull request closed without merging**
